// This file is generated by Wrangler for your Durable Objects.
// It is not intended to be edited.
// You can find the actual class in src/objects/SessionManager.ts

export interface Env {
  SESSION_MANAGER: DurableObjectNamespace;
}

declare global {
  namespace DurableObject {
    interface Env extends Env {}
  }
}